version: '3'

services:
  frontend:
    build:
      context: ClientApp
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: jgould
      POSTGRES_PASSWORD: db123
      POSTGRES_DB: bolo_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data:
